apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-receiver-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-receiver-go
  template:
    metadata:
      labels:
        app: webhook-receiver-go
    spec:
      containers:
      - name: receiver
        image: fykaa/kargo-webhook-receiver-go:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver-go
spec:
  selector:
    app: webhook-receiver-go
  ports:
  - port: 80
    targetPort: 8080
